#main file that was used to pack as exe
import tkinter as tk
from Deleter import deleter
window= tk.Tk()
window.geometry("340x340")
window.title("Temp Cleaner")
app_icon= tk.PhotoImage(file='apicon.png')
window.iconphoto(True,app_icon)
window.config(background='#0A0A0A')
button= tk.Button(window, text="Click here")
button.config(font=('Apple Garamond',20,'bold'))
icon= tk.PhotoImage(file='bin.png')
button.config(command=deleter)
button.config(activebackground='white')
button.config(activeforeground='black')
button.config(fg='white')
button.config(bg='black')
button.config(image=icon)
button.config(compound='top')
button.pack()
window.mainloop()
